# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{param_protected}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher J. Bottaro"]
  s.date = %q{2009-09-11}
  s.description = %q{Provides two class methods on ActiveController::Base that filter the params hash for that controller's actions.  You can think of them as the controller analog of attr_protected and attr_accessible.}
  s.email = %q{cjbottaro@alumni.cs.utexas.edu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/param_protected.rb",
     "tasks/param_protected_tasks.rake",
     "test/helpers_test.rb",
     "uninstall.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/cjbottaro/param_protected}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.2}
  s.summary = %q{Filter unwanted parameters in your controllers and actions.}
  s.test_files = [
    "test/accessible_except_test.rb",
     "test/accessible_only_test.rb",
     "test/app_root/app/controllers/accessible_except_controller.rb",
     "test/app_root/app/controllers/accessible_only_controller.rb",
     "test/app_root/app/controllers/application_controller.rb",
     "test/app_root/app/controllers/protected_controller.rb",
     "test/app_root/app/controllers/users_controller.rb",
     "test/app_root/config/boot.rb",
     "test/app_root/config/environment.rb",
     "test/app_root/config/environments/in_memory.rb",
     "test/app_root/config/environments/mysql.rb",
     "test/app_root/config/environments/postgresql.rb",
     "test/app_root/config/environments/sqlite.rb",
     "test/app_root/config/environments/sqlite3.rb",
     "test/app_root/config/routes.rb",
     "test/app_root/lib/console_with_fixtures.rb",
     "test/helpers_test.rb",
     "test/protected_controller_test.rb",
     "test/test_helper.rb",
     "test/users_controller_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
